const current = new Date();
const currentDate = `${current.getFullYear()}-${
  current.getMonth() >= 10
    ? current.getMonth() + 1
    : "0" + (current.getMonth() + 1)
}-${current.getDate() >= 10 ? current.getDate() : "0" + current.getDate()}`;

export const additionalInformation = [
  {
    id: 1,
    title: "What's your gender",
    register: "gender",
    required: true,
    select: true,
    maplist: [
      { titel: "", value: undefined, disabled: true },
      { titel: "male", value: "MALE" },
      { titel: "famale", value: "FAMALE" },
    ],
    invalid: "Select one of the options",
  },
  {
    id: 2,
    title: "Your marital status",
    register: "maritalStatus",
    required: true,
    select: true,
    maplist: [
      { titel: "", value: undefined, disabled: true },
      { titel: "married", value: "MARRIED" },
      { titel: "divorced", value: "DIVORCED" },
      { titel: "single", value: "SINGLE" },
      { titel: "widow/widower", value: "WIDOW_WIDOWER" },
    ],
    invalid: "Select one of the options",
  },
  {
    id: 3,
    title: "Your number of dependents",
    register: "dependentAmount",
    required: true,
    select: true,
    maplist: [
      { titel: "", value: undefined, disabled: true },
      { titel: "1", value: 1 },
      { titel: "2", value: 2 },
      { titel: "3", value: 3 },
      { titel: "4", value: 4 },
    ],
    invalid: "Select one of the options",
  },
  {
    id: 4,
    title: "Date of issue of the passport",
    type: "date",
    placeholder: "Select Date and Time",
    register: "passportIssueDate",
    required: true,
    select: false,
    invalid: "Incorrect date of passport issue date",
    max: currentDate,
  },
  {
    id: 5,
    title: "Division code",
    type: "number",
    placeholder: "000000",
    register: "passportIssueBranch",
    required: true,
    select: false,
    invalid: "The series must be 6 digits",
    max: "999999",
    min: "000000",
    minLength: 6,
    maxLength: 6,
  },
];

export const employmentInformation = [
  {
    id: 1,
    title: "Your employment status",
    register: "employmentStatus",
    required: true,
    select: true,
    maplist: [
      { titel: "", value: undefined, disabled: true },
      { titel: "unemployed", value: "UNEMPLOYED" },
      { titel: "self employed", value: "SELF_EMPLOYED" },
      { titel: "employed", value: "EMPLOYED" },
      { titel: "business owner", value: "BUSINESS_OWNER" },
    ],
    invalid: "Select one of the options",
  },
  {
    id: 2,
    title: "Your employer INN",
    type: "number",
    placeholder: "000000000000",
    register: "employerINN",
    required: true,
    select: false,
    invalid: "Department code must be 12 digits",
    max: "999999999999",
    min: "000000000000",
    minLength: 12,
    maxLength: 12,
  },
  {
    id: 3,
    title: "Your salary",
    type: "number",
    placeholder: "For example 100 000",
    register: "salary",
    required: true,
    select: false,
    invalid: "Enter your salary",
  },
  {
    id: 4,
    title: "Your position",
    register: "position",
    required: true,
    select: true,
    maplist: [
      { titel: "", value: undefined, disabled: true },
      { titel: "worker", value: "WORKER" },
      { titel: "mid manager", value: "MID_MANAGER" },
      { titel: "top manager", value: "TOP_MANAGER" },
      { titel: "owner", value: "OWNER" },
    ],
    invalid: "Select one of the options",
  },
  {
    id: 5,
    title: "Your work experience total",
    type: "number",
    placeholder: "For example 10",
    register: "workExperienceTotal",
    required: true,
    select: false,
    invalid: "Enter your work experience total",
    max: "99",
    min: "0",
    minLength: 1,
    maxLength: 2,
  },
  {
    id: 6,
    title: "Your work experience current",
    type: "number",
    placeholder: "For example 2",
    register: "workExperienceCurrent",
    required: true,
    select: false,
    invalid: "Enter your work experience current",
    max: "99",
    min: "0",
    minLength: 1,
    maxLength: 2,
  },
];
